# Generated by Django 3.2.19 on 2023-05-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.TextField()),
                ('category', models.TextField()),
                ('subCategory', models.TextField()),
                ('productType', models.TextField()),
                ('colour', models.TextField()),
                ('usage', models.TextField()),
                ('producttitle', models.TextField()),
                ('image', models.IntegerField()),
                ('imageURL', models.TextField()),
            ],
        ),
    ]
