# Generated by Django 3.2.19 on 2023-05-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_web', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
